# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-03-26 07:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('host', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, max_length=64, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('temperature', models.FloatField()),
                ('pressure', models.FloatField()),
                ('humidity', models.FloatField()),
                ('host', models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, to='labenviron.HostInfo')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='labdata',
            unique_together=set([('host', 'time')]),
        ),
    ]
